#!/bin/sh
# -*- tab-width:4;indent-tabs-mode:nil -*-
# ex: ts=4 sw=4 et
./rel/riak/bin/riak start
./rel/riak/bin/riak-admin bucket-type create indexes '{"props":{"chash_keyfun": "{chash_keyfun,chash_index_keyfun}"}}'
./rel/riak/bin/riak-admin bucket-type activate indexes
./rel/riak/bin/riak attach
